language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO_VERSION=1.7.1
addons:
  sauce_connect:
    username: "bertrandsvetchine"
    access_key: $SAUCE_ACCESS_KEY
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get update
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install selenium
  - pip install .
  - sudo apt-get install unzip
before_script:
  - curl "https://api.equinox.io/1/Applications/ap_pJSFC5wQYkAyI0FIVwKYs9h1hW/Updates/Asset/ngrok.zip?os=linux&arch=amd64&channel=stable" -o ngrok.zip
  - unzip ngrok.zip
  - ./ngrok -log stdout -authtoken $NGROK_TOKEN -subdomain django-payzen 8000 > /dev/null &
script:
  - python setup.py test --site $VADS_SITE_ID --certificate $VADS_CERTIFICATE
after_script:
  - killall ngrok
